apiVersion: v1
kind: Namespace
metadata:
  name: the-north-remembers

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: the-north-remembers-full-access
  namespace: the-north-remembers
rules:
- apiGroups: ["","extensions","apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
    - jobs
    - cronjobs
  verbs: ["*"]
