apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  labels:
    app: web
    name: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      name: webapi
  template:
    metadata:
      labels:
        app: web
        name: webapi
    spec:
      containers:
      - name: webapi
        image: 0gis0/webapi:v1
        ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: webapi-svc
spec:
  type: LoadBalancer
  selector:
    app: web
    name: webapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80