stages:
    - stage1
    - stage2

testjob:
    stage: stage1
    script:
      - env
    only:
      - develop

testjob1:
    stage: stage1
    script:
      - echo "job agrupado"
    only:
      - develop
    
testjob2:
    stage: stage2
    script:
      - echo "exit 1"
    only:
      - develop
    allow_failure: true
